# log_level = "debug"
log_level = "quiet"

[rocklet]
name = "rockhopper"
version = "0.0.11"
rev = "1"
maintainer = "Andrew Pennebaker <n4jm4@pm.me>"
summary = "metapackage generator"
description = "rockhopper generates installer packages for a wide variety of platforms"
copyright = "Copyright (C) 2026 Andrew Pennebaker"
license = "0BSD"
url = "https://github.com/mcandre/rockhopper"

[[pkg]]
image = "n4jm4/rockhopper:test-alpine-linux"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/x86_64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:test-alpine-linux"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "aarch64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/aarch64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:test-fedora"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/x86_64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:test-fedora"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "aarch64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/aarch64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:test-ubuntu"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "amd64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/x86_64-unknown-linux-musl"

[[pkg]]
image = "n4jm4/rockhopper:test-ubuntu"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
rocklet.data = "/mnt/rockhopper/.crit/bin/rockhopper-0.0.11/aarch64-unknown-linux-musl"
