# debug = true

# https://documentation.ubuntu.com/project/how-ubuntu-is-made/concepts/supported-architectures/
# https://github.com/tonistiigi/binfmt
# https://hub.docker.com/_/ubuntu

# Drop 32-bit support
# Work around buildx quirks
platforms = [
    "linux/amd64",
    # "linux/arm/v7",
    "linux/arm64/v8",
    # "linux/ppc64le",
    # "linux/riscv64",
    # "linux/s390x",
]
