# log_level = "debug"
log_level = "quiet"

# docker_args = []

[rocklet]
name = "raygun"
version = "1.2.3"
rev = "81"
maintainer = "Marvin the Martian <marvin@mars.test>"
summary = "Space modulator"
description = "Illudium Q-36 explosive space modulator"
# copyright = "Copyright (C) 1948 Marvin the Martian"
license = "0BSD"
url = "https://mars.test/"

[dest]
"usr/bin" = "bin"

# [docker_env]
# key = "value"

[[pkg]]
image = "n4jm4/rockhopper:alpine-linux"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "noarch"
# rocklet.dependencies = "bash"

[[pkg]]
image = "n4jm4/rockhopper:fedora"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "noarch"
# rocklet.dependencies = "bash"

[[pkg]]
image = "n4jm4/rockhopper:ubuntu"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "all"
# rocklet.dependencies = "bash"
