# log_level = "debug"
log_level = "quiet"

[rocklet]
name = "raygun"
version = "1.2.3"
rev = "81"
maintainer = "Marvin the Martian <marvin@mars.test>"
summary = "Where's the kaboom?"
description = "There was supposed to be an earth-shattering kaboom!"
# copyright = "Copyright (C) 1948 Marvin the Martian"
license = "0BSD"
url = "https://mars.test/"
# mount_path = "/mnt/rockhopper"
# data = "/mnt/rockhopper/rockhopper-data"
# specs = "/mnt/rockhopper/rockhopper-specs"
# cache = "/mnt/rockhopper/.rockhopper"

# [docker_env]
# key = "value"

# docker_args = []

[[pkg]]
image = "n4jm4/rockhopper:alpine-linux"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "noarch"
# rocklet.dependencies = "bash"

[[pkg]]
image = "n4jm4/rockhopper:fedora"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "noarch"
# rocklet.dependencies = "bash"

[[pkg]]
image = "n4jm4/rockhopper:ubuntu"
# rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "all"
# rocklet.dependencies = "bash"
